### ISSUE TITLE
eLife elocation ID

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#32]
Hi there

I have realised we are not sending our eLocation ID to PubMed, ie "the page number" e00000.

This means that the auto update mechanisms people like the typesetters use to via the PubMed API don't pick up a person readable elocation ID for use in reference lists and only pick up the DOI.

I'd like to be sending them the elocation ID too.

I've discovered this through the research and seeing what TNQ were doing with elocation IDs by forcing them into fpage/lpage tags....I wonder whether other publishers are doing something similar and this is causing an issue.

I'll investigate further, but wanted to flag this!

M

**Comment by Melissa37** [comment]
I have worked out what we need to do.

Add new entry to the XML supplied to PubMed

<ELocationID EIdType="pii">10.7554/e00776</ELocationID>


See: http://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.How_do_I_submit_citation_a

**Comment by Melissa37** [comment]
Can be done once new parser is deployed

**Comment by gnott** [comment]
Fixed in https://github.com/elifesciences/elife-poa-xml-generation/pull/215
