### ISSUE TITLE
Authors with multiple affiliations

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#33]
This is a new request to add to the workflow

http://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.What_information_should_be

Example of an author with multiple affiliations:

```
<Author>
<FirstName>Frank</FirstName
<LastName>Davis</LastName>
<AffiliationInfo>
<Affiliation>Department of Human Genetics, University of California, Los Angeles, California 90095, USA</Affiliation>
</AffiliationInfo>  
<AffiliationInfo>
<Affiliation>Lewis Sigler Institute for Integrative Genomics, Princeton University, Princeton, New Jersey, 08544, USA</Affiliation> 
</AffiliationInfo>  
</Author>
```

**Comment by Melissa37** [comment]
Is coded in, just needs releasing to live. Will add to the sample file too.

**Comment by Melissa37** [comment]
Added sample: https://github.com/elifesciences/elife-pubmed-feed/blob/master/elife-2015-10-02-114700.xml

**Comment by gnott** [comment]
This is done and deployed in https://github.com/elifesciences/elife-poa-xml-generation/pull/211
