### ISSUE TITLE
Expansion of the Publication Type values

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#35]
We are pleased to announce an expansion of the Publication Type values available for use by PubMed data providers.

Previously, data providers were limited to a small subset of potential Publication Type values: Journal Article, Published Erratum, Retraction of Publication, Editorial, Letter, and Review.

Effective immediately, data providers may use any of the following values in the PublicationType element, as appropriate:

Addresses
Bibliography
Case Reports
Classical Article
Classical Conference
Congresses
Consensus Development Conference
Consensus Development Conference, NIH
Correct and Republished Article
Editorial
Festschrift
Guideline
Interview
Journal Article
Lectures
Letter
Meta-Analysis
News
Newspaper Article
Patient Education Handout
Practice Guideline
Published Erratum
Retraction of Publication
Review
Video-Audio Media
Webcasts

The default value, Journal Article, will be added to citations if this tag is left blank or an invalid PublicationType is used. Please submit only one PublicationType per citation.

This list is also available in our Help: http://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.PublicationType_O.

**Comment by Melissa37** [comment]
Further expansion:

We are pleased to announce that PubMed data providers may submit the Publication Type values "Clinical Trial" and "Observational Study." Please keep in mind the following definitions:

CLINICAL TRIAL:
A work that reports on the results of a clinical study in which participants are assigned to receive one or more interventions so that researchers can evaluate the interventions on biomedical or health-related outcomes. The assignments are determined by the study protocol. Participants may receive diagnostic, therapeutic, or other types of interventions. While most clinical trials concern humans, this publication type may be used for clinical veterinary articles meeting the requisites for humans.

OBSERVATIONAL STUDY:
A work that reports on the results of a clinical study in which participants may receive diagnostic, therapeutic, or other types of interventions, but the investigator does not assign participants to specific interventions (as in an interventional study).


Also, the list of accepted Publication Types circulated in February contained two typographical errors:

"Correct and Republished Article" should be "Corrected and Republished Article."
"Classical Conference" should be "Clinical Conference."

The list of accepted Publication Type values below is correct and comprehensive:

Addresses
Bibliography
Case Reports
Classical Article
Clinical Conference
Clinical Trial
Congresses
Consensus Development Conference
Consensus Development Conference, NIH
Corrected and Republished Article
Editorial
Festschrift
Guideline
Interview
Journal Article
Lectures
Letter
Meta-Analysis
News
Newspaper Article
Observational Study
Patient Education Handout
Practice Guideline
Published Erratum
Retraction of Publication
Review
Video-Audio Media
Webcasts

As a reminder, the default value, Journal Article, will be added to citations if this tag is left blank or an invalid Publication Type value is used. Please submit only one Publication Type per citation.

If you have any  questions or concerns, please feel free to contact us at publisher@ncbi.nlm.nih.gov.

**Comment by Melissa37** [comment]
Have asked Andy/Peter whether we should consider any changes. Unlikely as would involve a lot of work to get this into the automated PubMed generation process. So will close for now and re-open if they have strong wishes!

**Comment by gnott** [comment]
Right now we use three types only in Pubmed submissions,

EDITORIAL
PUBLISHED ERRATUM
JOURNAL ARTICLE
