### ISSUE TITLE
Updated requirements and potential procedures

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#38]
PubMed Publisher DTD URL.

The PubMed Publisher DTD has a new home:
https://dtd.nlm.nih.gov/ncbi/pubmed/in/PubMed.dtd.

Please use the following header:
<!DOCTYPE ArticleSet PUBLIC "-//NLM//DTD PubMed 2.6//EN"
"https://dtd.nlm.nih.gov/ncbi/pubmed/in/PubMed.dtd">

Replacing non-Ahead of Print citations.

Since the release of the PubMed Data Management (PMDM) system in October 2016, data providers could only submit Replaces files for Ahead of Print citations. Edits to citations in any other status had to be completed in PMDM.

We now accept Replaces files for non-Ahead of Print citations to correct data in the following fields:

* AuthorList (includes Author, Affiliation, Identifier)
* InvestigatorList (includes Investigator, Affiliation, Identifier)
* Pagination
* ELocationID
* OtherAbstract
* DOI
* PII

Although the update is targeted, the Replaces file must be valid XML. Do not, for example, submit only the AuthorList section. Our loader will compare the content in the above fields in the Replaces file with the existing PubMed citation and only modify the content if it is different. Ahead of Print citations will continue to be replaced entirely by the Replaces file.

For more information about correcting errors in PubMed, please see
https://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.Correcting_Errors_in_PubMe

Instructions for Replaces files are available here:
https://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.Instructions_for_Replaceme

Data in non-English languages.

Please note that we can accept <VernacularTitle> and <OtherAbstract> data for any non-English languages, including Japanese, Russian, and other languages with non-Latin-based characters. Instructions for including non-English content in submissions are available here:
https://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.Instructions_for_articles

Conflict of Interest (COI) Statements.

If a published article includes a Conflict of Interest (COI) Statement,  please include it in your XML citation data submission to PubMed. These COI statements should be provided in a new element: <CoiStatement>. This element occurs after the <Abstract> and <CopyrightInformation> tags, and before the <ObjectList>.

These COI statements can also be added to citations in PMDM. The Conflict of Interest field appears in the Abstract section, just below Copyright Information.

**Comment by gnott** [comment]
I think we already add Replaces tag for when a non-Ahead of Print article submission goes through. A recent example could be https://doi.org/10.7554/eLife.23190, on which, I believe, some author affiliations were changed about a week later. The PubMed deposit of June 15th was presumably successful, and the affiliations on the PubMed site match what is on the website https://www.ncbi.nlm.nih.gov/pubmed/?term=10.7554%2FeLife.23190.

@Melissa37  is there more to do here on this issue? Or were you just making a note about this change to PubMed processes?

**Comment by gnott** [comment]
I think my question still stands that I think we already do this logic for adding ``<Replaces>`` tags, if you are able to please confirm @Melissa37.

**Comment by Melissa37** [comment]
@JGilbert-eLife I have assigned this issue to you as you can confirm - and we may need to change the production processes?

I missed/did not really understand to implications of this earlier.

So, we do not need to use the PubMed tool because the bot sends replacement files to PubMed anyhow when we publish new versions?

However, my understanding is that it does not work because we get numerous rejections from PubMed via their PubMed Loader report, and it was this.

@gnott have you updated the code recently?
I'm still a bit confused!

**Comment by gnott** [comment]
I don't think there have been many recent changes of the PubMed deposit code we run right now. My memory of recent deposit failures were due to ``<Replaces>`` tag a logic and in the PubMed report it says it cannot find the DOI in order to replace it. This happened in some specific cases where I think the v1 was not deposited to PubMed and then all v2 articles get a ``<Replaces>`` tag added. This bug is more related to our workflow than the PubMed deposit generation code itself. There's a JIRA ticket somewhere with a potential fix which we should make sure is integrated into the new release of the entire package.

Or, it could be something completely different you are thinking of.

**Comment by JGilbert-eLife** [comment]
I had not noticed but our last PubMed failure was back at the start of August!

I guess that means we indeed don't have to manually update PubMed when we issue new versions of VoRs any more. Which is very nice!

**Comment by Melissa37** [comment]
Fab! Can we do a note to self to check this next time we do change metadata?

Thanks all!

M

**Comment by JGilbert-eLife** [comment]
28985 was updated yesterday with a new version and PubMed has indeed updated to reflect that!

We did get PubMed rejections on silent corrections to 26693 and 24179, though not on 30883, oddly enough.

Elife|2017|6||e26693|Huang HT|10.7554/eLife.26693|28926338|REJECTED: Article Matches PmID=28926338, which is not in "[PubMed - as supplied by publisher]" status
Elife|2017|6||e24179|Lin A|10.7554/eLife.24179|28337968|REJECTED: Article Matches PmID=28337968, which is not in "[PubMed - as supplied by publisher]" status

Not sure if that is related to their being silent corrections or older articles . . . ?

Any thoughts @gnott ?

**Comment by gnott** [comment]
Yes, I believe this is because those two were submitted as part of a silent correction of v1 version articles. I've identified some possible enhancements to the new code logic in a new issue https://github.com/elifesciences/elife-pubmed-feed/issues/57. The presence of a v1 does not necessarily mean we should omit the ``<Replaces>`` tag from the PubMed deposit, so we could set it prior to generating the deposit if we know it is part of a silent correction, or if we know it has been indexed in PubMed already.

**Comment by Melissa37** [comment]
How about these from yesterday:

Elife|2016|5||e11450|Kaplan ES|10.7554/eLife.11450|26943618|REJECTED: Article Matches PmID=26943618, which is not in "[PubMed - as supplied by publisher]" status
Elife|2013|2||e00269|Yu S|10.7554/eLife.00269|23543845|REJECTED: Partial match
Total processed: 2 article(s), 2 were rejected

**Comment by gnott** [comment]
Yes, I think the two examples you provided above fit the situation that is currently not covered: a silent correction of a v1. The logic for these ones should be improved, although probably via a workflow generating the PubMed deposit itself, which knows more context about the status of previous PubMed deposits for the article.

**Comment by Melissa37** [comment]
Cool, I think the logic should be that silent corrections don't get delivered to PubMed at all.
Then we'd not have rejections from them.
They should not go as no metadata should change in a silent correction, they are only used for file changes or tagging changes, so this has no effect on PubMed.

Thanks!
M
