### ISSUE TITLE
Adding Funding to data deposits

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#39]
We will now accept grant data in citation data submissions. The grants should be provided in the ``<ObjectList>`` as follows:

```
<ObjectList>
<Object Type="grant">
<Param Name="id">12345</Param>
<Param Name="grantor">Wellcome Trust</Param>
</Object>
</ObjectList>
```

Grant data can also be added to existing PubMed citations using PMDM. For instructions on how to add grants in PMDM, please see:
https://www.ncbi.nlm.nih.gov/pubmed/management/help/editing-single/#grants

**Comment by Melissa37** [comment]
From PubMed help: Can I submit grant information?

Yes. The grants should be provided in the <ObjectList> as follows:

<ObjectList>
<Object Type="grant">
<Param Name="id">12345</Param>
<Param Name"grantor">Wellcome Trust</Param>
</Object>
</ObjectList>
What is an Article Identifier?

All Article Identifiers are optional. An Article Identifier can take one of two forms; a PII or a DOI.

A PII, or Publisher Item Identifier, is any internal reference identifier used in the publishing process. This identifier is assigned by the publisher.

A DOI, or Digital Object Identifier, is a number assigned by an international organization. The DOI System is a system for identifying and exchanging intellectual property in the digital environment. DOIs are issued to registrants by the DOI Registration Agency. More information about this standardized format can be obtained at http://www.doi.org/.

A DOI can be provided in two different elements: ELocationID and ArticleId. A DOI should be supplied in the standard format, e.g., 10.xxx/xxx. Do not include any leading characters like “doi:” or submit the DOI as a URL.

Article Identifiers (PII and DOI) are available for use in LinkOut, which allows providers to create links from article citations in PubMed to the full-text article hosted on the publisher websites.

**Comment by Melissa37** [comment]
@gnott are we ignoring funding that does not have a crossref ID and not sending it to PubMed? It does not say it has to have an ID, also the PII can be a publishers assigned ID...

**Comment by gnott** [comment]
For funding I've tried using each the award-id and the crossref fundref id in the Pubmed ``<Param>`` tag. Previewing it on the Pubmed citation checker, neither really produces a full list of all the grants included in the deposit.

It would be helpful to have some clarification on when adding grant data whether it should have a doi Param, or what value should go into the id Param. The one small sample in the Pubmed help book is not too clear to me.

**Comment by Melissa37** [comment]
Thanks, have emailed PubMed and cc'd you in

**Comment by Melissa37** [comment]
From PubMed:

I’m sorry for the misunderstanding.  The grant is a field with limited allowed values:  <Param Name="grantor">Wellcome Trust</Param>.  We do not control or validate the attribute “id”.  So you can enter the number without checking an authority list.  The “id” attribute is optional.

Unfortunately, there is not a downloadable list of grant names or API. Updates are announced in the NLM Technical Bulletin.  For example: https://www.nlm.nih.gov/pubs/techbull/ja17/ja17_pmc_funding_organization_wellcome_trust_dbt_india_alliance.html 
You could truly submit any combination of the information from the description in the grant information table, but it is best practice to send in the “Full Institute/Organization Name”.  For institutes that have divisions listed as well as the overarching agency, please include both, e.g., “NCI Division of Cancer Treatment.”

**Comment by gnott** [comment]
Thanks for providing the details @Melissa37 and PubMed!

I think if the name and id for each grant is included in the deposit file, then it should be feature complete as far as the software goes.

**Comment by Melissa37** [comment]
HI G

We received this from PubMed. I don't think it changes anything, but wanted to send it to you for checking anyhow:

Please include funding information in citation data sent to PubMed when the research was supported by one or more grants. Supplying these details will enable users to discover the citations when searching by funding body or grant in PubMed.

If an article has supporting grant information, it should be provided in the <ObjectList> as follows:

<ObjectList>
<Object Type="grant">
<Param Name="id">12345</Param>
<Param Name="grantor">Wellcome Trust</Param>
</Object>
</ObjectList>

When you supply a grantor name exactly as it appears in our list (https://www.nlm.nih.gov/bsd/grant_acronym.html), we will automatically display the appropriate country on the citation in PubMed. You may supply grants that do not appear on the list; however, we will not append the country name for other organizations.

We encourage you to include these data in your XML file submissions and/or add the data to your citations using PMDM. 

RESOURCES

*   List of funding organizations found in the GR field in MEDLINE/PubMed: https://www.nlm.nih.gov/bsd/grant_acronym.html 

*   How to submit grant information in PubMed XML: https://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.Can_I_submit_grant_informa 

*   How to add or edit grant information in PMDM:  https://www.ncbi.nlm.nih.gov/pubmed/management/help/editing-single/#grants

**Comment by gnott** [comment]
I think we discussed at the time but I cannot remember the exact outcome. Was it possible the typesetters were going to consider the list of funders for inclusion in the JATS XML? If we were going to try it on the PubMed submission side, I think trying to fuzzy match any funder name to the strict list provided by PubMed was going to be a challenge, and we probably decided to postpone attempting it.

**Comment by Melissa37** [comment]
Coolio, all good.
Thanks
M

**Comment by gnott** [comment]
Looking at the PubMed generation code, I think we add funding since December 2017. Do you remember @Melissa37, was an outstanding issue that the Funder name/id was supposed to match the allowed values PubMed accepts? Is that something Schematron does? Is there anything more we are to do with sending funding data to PubMed, or is it possible we can close this issue?

**Comment by Melissa37** [comment]
Hi there

Yes I think we can close this. I have followed up with them (long time later) to say we match to the Crossref Open Funder Registry and don't have the capacity to also try and match their terminology, if different.

Thanks!

Melissa
