### ISSUE TITLE
Creating links between related citations

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#40]
Last year, we began accepting the PMID, DOI, or PII of the original citation in the submissions for errata and retractions. This ensures a link between the original citation and related citation is created in PubMed as soon as the related citation is loaded to PubMed. This year we are extending this capability to all related article types, i.e.: errata, retractions, comments, reprints, updates, patient summaries, and datasets.
When submitting citations for these types of articles, please include the PMID, DOI, or PII of the original citation in the submission, e.g.:
```
<ObjectList>
<Object Type="comment">
<Param Name="type">pmid</Param>
<Param Name="id">27725804</Param>
</Object>
```
For more information on creating these links when submitting citation data, please see:
https://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.How_should_I_submit_citati
In addition, these links can be added to citations using PMDM (https://www.ncbi.nlm.nih.gov/pubmed/management/). To add a link to an existing PubMed citation, find the citation in PMDM and add the PMID of the related citation in the "Comments, Errata, Retractions, and Other Related Articles" section. For instructions on how to add these links in PMDM, please see:
https://www.ncbi.nlm.nih.gov/pubmed/management/help/editing-single/#comment-correction

**Comment by gnott** [comment]
What are the types of related articles we want to support starting out? Will we find the relatedness of the articles inside the article XML itself, or will we also consult external data sources to determine the related items for a particular article?

**Comment by Melissa37** [comment]
My understanding is, that when we publish an official correction, we send the XML to PubMed for that "article". Do we add to that PubMed XML the DOI of the original research article it refers to, using this tagging:

```
xml
<ObjectList>
<Object Type="Correction">
<Param Name="type">doi</Param>
<Param Name="id">10.7554/eLife.30178</Param>
</Object>
</ObjectList>
```

If not, I think that's what we should be doing.

Also, for datasets, I 've emailed them and cc'd you in:

We are currently updating our PubMed deposit information and are adding enhancements based on update emails we've had from you over the past couple of years.

Question 1
Regarding submitting datasets, I am a bit confused by the documentation.
Here an object type value of "Dataset" is provided, but here Dataset repository names are provided as the Dataset object type value.

Using the first example, I'd assume the tagging should be:
<Object Type="Dataset">
<Param Name="type">Dryad</Param>
<Param Name="id">10.5061/dryad.2f050</Param>
</Object>
But for the second the tagging should be:
<Object Type="Dryad">
<Param Name="id">10.5061/dryad.2f050</Param>
</Object>
</ObjectList>

Question 2
What cited datasets are you expecting to be deposited with PubMed. Is it only the datasets that were generated as part of the study and so are directly linked to the article, or all datasets that are referenced by the article?
I am assuming its the first, but wanted to check.

I assume we'd need to start sending them our generated datasets:

```
xml
    <p>The following dataset was generated:</p>
                <p>
                    <related-object content-type="generated-dataset"
                        source-id="https://github.com/elifesciences/XML-mapping/blob/master/elife-00666.xml"
                        source-id-type="uri" id="dataset1">
<!--UPDATE: Add @collab-type="author" attribute. Change order of author name to first initial then surname-->  
                        <name>
                            <surname>Harrison</surname>
                            <given-names>M</given-names>
                        </name>
                        <collab collab-type="author">York University</collab>
<!--UPDATE: Remove all punctuation that was prevously surrounding the tags--> 
                        <year iso-8601-date="2016">2016</year>
                        <source>xml-mapping</source>
                        <ext-link ext-link-type="uri"
                            xlink:href="https://github.com/elifesciences/XML-mapping/blob/master/elife-00666.xml"
                            >https://github.com/elifesciences/XML-mapping/blob/master/elife-00666.xml</ext-link>
                        <comment>Publicly available on GitHub</comment>
                    </related-object>
                </p>
```
However, the way we are tagging this is not conducive to collecting the right information in order to pass it on to PubMed.

JATS4R now has a recommendation for tagging Data Availability Statements, which we've not implemented.
I think we'd go for http://jats4r.org/data-availability-statements example 4 (Example 4: Data externally archived – full citations included as a ref list within the DAS). This would give us the information we'd need to parse it out for PubMed:

```
xml
<title>Data Availability</title>
<p>The following datasets were generated for this study:</p>
<ref-list>
<ref id="pone.0167830.data001">
<label>D1</label>
<element-citation publication-type="data" specific-use=”isSupplementedBy”>
<name><surname>Read</surname><given-names>K</given-names></name>
<data-title>Sizing the Problem of Improving Discovery and Access to NIH-funded Data: A Preliminary Study (Datasets)</data-title>
<source>Figshare</source>
<year>2015</year>
<pub-id pub-id-type="doi" assigning-authority="figshare" xlink:href="https://doi.org/10.6084/m9.figshare.1285515">https://doi.org/10.6084/m9.figshare.1285515</pub-id>
</element-citation>
</ref>
```

We'd have the Source and assigning-authority, which should hopefully match one of the pubMed values: https://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.ObjectList_O

I am sorry Graham. I don't think this is ready yet for the PubMed deliveries and think it needs work on in editorial and production first.
I'll bring Maria into the loop and we need to chat with her and @thewilkybarkid about this too.

**Comment by gnott** [comment]
A couple parts here:

1. Relatedness between a correction and the article to which is refers

When the library processes a correction article which has related article tagging in it, it adds a related object in the Pubmed deposit. For example in the tests correction article 10.7554/eLife.15743 refers to the article it corrects like this:

```
<ObjectList>
<Object Type="Erratum">
<Param Name="type">doi</Param>
<Param Name="id">10.7554/eLife.05462</Param>
</Object>
```

After Pubmed processes this ``"Erratum"`` Object, then the two articles are linked together in Pubmed with an "Erratum In" / "Erratum for" link between the two Pubmed records.

2. Adding datasets

There is a separate issue for datasets issue https://github.com/elifesciences/elife-pubmed-feed/issues/61, which I think duplicates most of the information here. The conversation about datasets can continue there?

I will close this issue.

**Comment by Melissa37** [comment]
Hi there

Is the code updated for Retraction, now that we've got one!

M

**Comment by gnott** [comment]
PR https://github.com/elifesciences/elife-pubmed-feed/issues/72  should have added the retraction support.

I think I see in the elife-bot project it is not reinstalling the pubmed library properly. I will update that, and then we can resubmit the retraction to PubMed.

**Comment by Melissa37** [comment]
Cool, thanks.
However, I think we can do it manually via their tool for publishers, and the resupply might not work.
If you can reinstall the library, I'll ask the team to update this retraction.
Thanks!
M

**Comment by Melissa37** [comment]
should we close this issue once you've reinstalling the pubmed library, or is that covered in another issue and we can close now?

Thanks!

**Comment by Melissa37** [comment]
HI @gnott This can be closed can't it as you are adding links? Ir is that not done yet and I misread this?

**Comment by gnott** [comment]
I didn't remember doing this, but in the case of a correction or retraction article, an appropriate `<Object>` tag is added to the PubMed deposit output.

I think we're ok to close this issue.
