### ISSUE TITLE
Adding clinical trial data

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#41]
PubMed data providers may now include ClinicalTrials.gov identifiers in their XML citation data submitted to PubMed.
Sample XML:
```
<ObjectList>
<Object Type="ClinicalTrials.gov">
<Param Name="id">NCT00000125</Param>
</Object>
</ObjectList>
```
Supplying these identifiers will create a link from the PubMed citation to the study on the ClinicalTrials.gov website.
As a reminder, data providers may submit the Publication Type values "Clinical Trial" and "Observational Study." Please keep in mind the following definitions:
CLINICAL TRIAL:
A work that reports on the results of a clinical study in which participants are assigned to receive one or more interventions so that researchers can evaluate the interventions on biomedical or health-related outcomes. The assignments are determined by the study protocol. Participants may receive diagnostic, therapeutic, or other types of interventions. While most clinical trials concern humans, this publication type may be used for clinical veterinary articles meeting the requisites for humans.
OBSERVATIONAL STUDY:
A work that reports on the results of a clinical study in which participants may receive diagnostic, therapeutic, or other types of interventions, but the investigator does not assign participants to specific interventions (as in an interventional study).
Options

**Comment by Melissa37** [comment]
https://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp

**Comment by gnott** [comment]
I would like to discuss this a little more, regarding the support for parsing clinical trial data from the XML. I'm not sure the structure of it and how easily the clinical trial ID values can be extracted.

**Comment by Melissa37** [comment]
Hi G, I think tis is another one that might need to go back into Pending.
There is a JATS4R recommendation being worked on currently, and I hope it will be released by the end of the year.
It will incorporate a lot of the work Crossref have done on this and we're looking to have very structured info that could easily be parsed...

This is not the definite tagging, but structure like this would work?

```
xml
<related-object link-type="clinical-trials-registry" source-type="clinical-trials-registry"  document-id="ISRCTN69423238" xlink:href="http://dx.doi.org/10.1186/ISRCTN69423238">
<source id=“10.11810/isrctn”>ISRCTN</source>
</related-object> 

```

The JATS4R group have checked and PubMed recognises the same defined list of clinical trial registries that Crossref do.

**Comment by gnott** [comment]
Thanks for the update. It can stay in "Deposit Enhancements" milestone, because I created a "Deposit Enhancements - actionable" milestone for things that are ready to implement now.

**Comment by Melissa37** [comment]
A useful conversation between PLOS and PubMed:

PLOS:

PLOS would like to implement JATS4R's Clinical Trial tagging recommendations and begin submitting the relevant data to Crossref and PubMed. The JATS4R recommendation suggests tagging either the registry DOI or registry name as it appears in Crossref's list of WHO-approved registries.
![screen shot 2018-06-21 at 14 20 19](https://user-images.githubusercontent.com/6051876/41721646-641d7dca-755e-11e8-837f-ef37a212e676.png)

Per the table below, there are a few discrepancies between Crossref's list of names and PubMed's documented allowable values for Object/@Type. Additionally, some of PubMed's documented allowable values are actually giving validation errors in PubMed's Citation File Validator.

PubMed:
Thank you for your interest in submitting clinical trial numbers to PubMed.  After much discussion with clinical trials staff at NIH, we will not be changing the registry names “EudraCT” or “UMINCTR” in our systems since these are the acronyms in use by the respective registries.  We can, however, allow the submission of UMIN and EU-CTR and then normalize these acronyms on our end to make the submissions easier for our data providers.  Essentially, submitting either acronym would resolve to the proper value for our systems.  I am going to forward this request to our development team.  Although I cannot predict when the work will be complete, I will certainly update you as it proceeds.
At this time we have no plans to incorporate UTN as a registry name/value in our systems, or to replace the registry name with the DOI.
Today we began redirecting the “old” citation validator to a newer validator that is part of our PMDM interface. You can find the new validator at https://www.ncbi.nlm.nih.gov/pubmed/management/validator/.   If you see errors for "JMACCT" and "TCTR" with the new validator, could you please send me the file so that I can investigate further?
If you have any questions or concerns, please contact us at publisher@ncbi.nlm.nih.gov.

PLOS: 
That's so great, Marie. Thank you so much for allowing publishers to send UMIN and EU-CTR and normalizing on your end. Very helpful. If an author supplies us with a UTN number, we will plan to exclude it from the PubMed submission (it will still appear in the Abstract, but will not be captured in Object/@Type).
As for the earlier validation errors, I just tested out the new citation validator and it appears any value is now accepted for Object/@Type, even completely bogus ones.  However, only the following ones actually get rendered under "Secondary source IDs" in the preview citation:

![pastedimage](https://user-images.githubusercontent.com/6051876/41721715-93dbbbee-755e-11e8-8a4b-8893f61c3a9b.png)

Looks like the rendering software will need to be updated to also render:


UMINCTR
JMACCT
TCTR
Attached is the sample file I used to generate the screenshot above. We're still a ways off from deploying this feature as we'll need to update our submission system, transforms and rendering software, but the information you have provided will help us finalize the work requests.

**Comment by gnott** [comment]
@Melissa37, do you think we might consider adding clinical trials to PubMed deposits too, after we've finished adding them to Crossref deposits?

**Comment by Melissa37** [comment]
Yes Yes yes, that would be great, thanks :-)

M

**Comment by Melissa37** [comment]
Coolio, this can go back on the to do list once Crossref is implemented? Or at the same time?

**Comment by gnott** [comment]
Code is ready for this in PR https://github.com/elifesciences/elife-pubmed-xml-generation/pull/50.

If the article has clinical trials then the data will be added to the PubMed XML deposit generated.

**Comment by fred-atherden** [comment]
Just confirming this is working with https://pubmed.ncbi.nlm.nih.gov/33650967/:
<img width="325" alt="Screenshot 2021-03-25 at 09 03 46" src="https://user-images.githubusercontent.com/43879983/112447263-0753e600-8d49-11eb-95f9-4e673b4dfe13.png">

**Comment by gnott** [comment]
Looks as it should which is a relief, thanks for checking on it Fred.
