### ISSUE TITLE
Adding equal contributions to PubMed XML deposit

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#43]
The PubMed Publisher DTD (https://dtd.nlm.nih.gov/ncbi/pubmed/in/PubMed.dtd) allows data providers to indicate equal contribution among authors by using the EqualContrib attribute of the Author element. The default value for the attribute is "N," indicating non-equal contribution. In the example below, the first two authors contributed equally.

```
<AuthorList>
<Author EqualContrib="Y">
<FirstName>Katherine</FirstName>
<LastName>Anderson</LastName>
<AffiliationInfo>
<Affiliation>Georgetown University</Affiliation>
</AffiliationInfo>
</Author>
<Author EqualContrib="Y">
<FirstName>Edward</FirstName>
<LastName>Scarborough</LastName>
<AffiliationInfo>
<Affiliation>Mayo Clinic</Affiliation>
</AffiliationInfo>
</Author>
<Author>
<FirstName>Joanna</FirstName>
<LastName>Kay</LastName>
<AffiliationInfo>
<Affiliation>Georgetown University</Affiliation>
</AffiliationInfo>
</Author>
</AuthorList>
```

Instructions for how to indicate equal contribution in PMDM and in your XML submissions are available here:

https://www.ncbi.nlm.nih.gov/pubmed/management/help/editing-single/#equalcontrib
https://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.How_can_I_indicate_equal_c

PubMed Data Provider Support Team - publisher@ncbi.nlm.nih.gov
National Center for Biotechnology Information
National Library of Medicine

**Comment by gnott** [comment]
I'm adding in the logic now to the new generation library. It will add the ``EqualContrib="Y"`` attribute when the contributor contributes equally, and it will not bother to add ``EqualContrib="N"`` if they did not contribute equally (which I believe can be omitted).

Trying the generated file in the PubMed citation checker at https://www.ncbi.nlm.nih.gov/pubmed/citcheck/  I do not see any visual difference when an Author is set as having contributed equally. I guess internally to the PubMed system it makes a difference?
