### ISSUE TITLE
Source additional non-eLife XML to test the code

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-pubmed-feed#54]

**Comment by gnott** [comment]
Hi Melissa, could you please suggest or provide an open licensed article in addition to the BMJOpen article we've used in tests so far?

I tried the other "cstp" sample, except when I try to validate it on the PubMed site, it says their ISBN is not valid. Perhaps PubMed only looks at journals that it would accept?

So, I'd be wanting at least one other sample from a journal that would actually submit to PubMed.

**Comment by Melissa37** [comment]
Sent you two samples from Psychologica Belgica via email.

**Comment by gnott** [comment]
Samples added in https://github.com/elifesciences/elife-pubmed-xml-generation/pull/2, thanks @Melissa37 !
