### ISSUE TITLE
Contributor on-behalf-of

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-pubmed-feed#56]
Building tests for the new kitchen sink XML, I see in the article XML there is an ``<on-behalf-of>`` tag,

```
<on-behalf-of>for the eLife Staff Team</on-behalf-of>
```

@Melissa37 are you able to comment further of whether this value would be included in a PubMed deposit?

There's just a brief mention of on-behalf-of in issue https://github.com/elifesciences/elife-pubmed-feed/issues/7  from long ago about group authors.

**Comment by Melissa37** [comment]
I have an email exchange out with Andy because PubMed do not account for on-behalf-of but reading between the lines they would treat it as an author, as long as the "groups" contribution was valid.

**Comment by Melissa37** [comment]
Just confirmed with Andy- should be treated as a group author.

Thanks!
M

**Comment by gnott** [comment]
I'm trying to add an ``on-behalf-of`` value as a group. It looks like if there is a ``<Group><GroupName>`` then it requires an ``<IndividualName>``. That would require at a minimum a ``<LastName>`` I think. We could add the on-behalf-of value as both the GroupName and the LastName in order to create a valid deposit.

Is that sounding ok, or does the inclusion of on-behalf-of need more analysis?

**Comment by Melissa37** [comment]
Hi there

No more analysis needed, that's perfect.

Thanks
M

**Comment by gnott** [comment]
It looks like the compatible way and best looking result is to produce this

```
<Group>
<GroupName>for the eLife Staff Team</GroupName>
<IndividualName>
<FirstName EmptyYN="Y"/>
<LastName>for the eLife Staff Team</LastName>
</IndividualName>
</Group>
```

On Pubmed it will end up looking like this under the Collaborators list

![image](https://user-images.githubusercontent.com/1779115/32501175-3032d7a0-c38c-11e7-9471-00f4989456ed.png)
