### ISSUE TITLE
<PublicationType> updates

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#59]
The approved list on PubMed is:
Addresses
Bibliography
Case Reports
Classical Article
Clinical Conference
Clinical Trial
Congresses
Consensus Development Conference
Consensus Development Conference, NIH
Corrected and Republished Article
Editorial
Festschrift
Guideline
Interview
Journal Article
Lectures
Letter
Meta-Analysis
News
Newspaper Article
Observational Study
Patient Education Handout
Practice Guideline
Published Erratum
Retraction of Publication
Review
Video-Audio Media
Webcasts

Our XML is delivering in all caps, not in sentence case as they request.

Also, need to confirm our article type mapping is still correct:
Article type
Research article (RA) --> Journal Article
Short report (SR) --> Journal Article
Research advance (ADV) --> Journal Article
Feature (F)
Feature Research (FR) --> Journal Article
Insight (I) --> Editorial
Editorial (ED) --> Editorial
Registered report (RR) --> Journal Article
Replication study (RS) --> Journal Article
Tools and resources (TR) --> Journal Article

**Comment by gnott** [comment]
Actions for now will be 

* to change the case sensitivity of values, 
* look at whether all the eLife article types are specified, and
* see if these values should be moved to the configuration file to be customised on a per-journal basis.

**Comment by Melissa37** [comment]
cool, thanks.
M

**Comment by gnott** [comment]
Feature (F)
@Melissa37  could you please confirm, is this Editorial or Journal Article for PubMed deposits?

**Comment by Melissa37** [comment]
Lets go for Journal Article
