### ISSUE TITLE
ArticleIdList

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#60]
We are only providing the DOI in this section, but should also be providing the pii as well?

**ArticleIdList (O/R)**

The list of Article Identifiers. This tag is Required if ArticleId is present.

ArticleId (R)

The Article Identifier. The ArticleId tag includes the IdType attribute, which may include only one of the following values for each identifier:

pii - controlled publisher identifier (default value)
doi - Digital Object Identifier
DOI in ArticleId is used to generate LinkOut links to the full-text and will also display at bottom of the citation.

DOI should be supplied in the standard format, e.g., 10.xxx/xxx. Do not include any leading characters like “doi:” or submit the DOI as a URL.

Click here for more information about Article Identifiers.

**Comment by gnott** [comment]
I've done a few small changes. 

If an ``elocation-id`` is present, like ``<elocation-id>e15743</elocation-id>`` in the JATS XML, it will continue to be included in a Pubmed ``<ELocationID EIdType="pii">e15743</ELocationID>`` tag.

If there is an ``article-id`` tag, like ``<article-id pub-id-type="publisher-id">15743</article-id>``, then it will be included in a Pubmed ``<ArticleId IdType="pii">15743</ArticleId>`` tag.

I think this is the right place for each of these values which are slightly different, or very different in the case of the BMJOpen sample, or non-existent on some other samples.

**Comment by Melissa37** [comment]
Fab, sounds perfect :-)
