### ISSUE TITLE
Add multiple affiliations for authors

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#62]
Are we doing this already Graham?

**Can I submit multiple affiliations for one author?**

Yes. Please see the following example:

<Author>
<FirstName>Frank</FirstName
<LastName>Davis</LastName>
<AffiliationInfo>
<Affiliation>Department of Human Genetics, University of California, Los Angeles, California 90095, USA</Affiliation>
</AffiliationInfo>
<AffiliationInfo>
<Affiliation>Lewis Sigler Institute for Integrative Genomics, Princeton University, Princeton, New Jersey, 08544, USA</Affiliation>
</AffiliationInfo>
</Author>

**Comment by gnott** [comment]
We are already submitting multiple affiliations per author, if it is provided in the XML, yes.

**Comment by gnott** [comment]
I will close this as done.

There is an example in the test cases (https://github.com/elifesciences/elife-pubmed-xml-generation/blob/develop/tests/test_data/elife-pubmed-02935-20170717071707.xml) from which I will include a snippet of here

```
<Author>
<FirstName>Jyoti</FirstName>
<LastName>Nangalia</LastName>
<AffiliationInfo>
<Affiliation>
Cancer Genome Project, Wellcome Trust Sanger Institute, Hinxton, United Kingdom
</Affiliation>
</AffiliationInfo>
<AffiliationInfo>
<Affiliation>
Cambridge University Hospitals NHS Foundation Trust, Cambridge, United Kingdom
</Affiliation>
</AffiliationInfo>
<AffiliationInfo>
<Affiliation>
Department of Haematology, University of Cambridge, Cambridge, United Kingdom
</Affiliation>
</AffiliationInfo>
</Author>
```

On PubMed, these show with multiple superscript ordinals, 1,2,3 like this
![image](https://user-images.githubusercontent.com/1779115/31681000-d07d8204-b32a-11e7-9a3d-431dff5d38f9.png)
