### ISSUE TITLE
Indicating equal contributions

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#63]
Our XML example:
```
xml
<contrib contrib-type="author" corresp="yes" equal-contrib="yes" id="author-00001" deceased="yes">
```

Convert equal-contrib="yes" to <Author EqualContrib="Y">

From the PubMed guidelines:

**How can I indicate equal contribution among authors?**

Use the EqualContrib attribute of the Author element to indicate equal contribution among authors. The default value for the attribute is "N," indicating non-equal contribution. In the example below, the first two authors contributed equally.

<AuthorList>
<Author EqualContrib="Y">
<FirstName>Katherine</FirstName>
<LastName>Anderson</LastName>
<AffiliationInfo>
<Affiliation>Georgetown University</Affiliation>
</AffiliationInfo>
</Author>
<Author EqualContrib="Y">
<FirstName>Edward</FirstName>
<LastName>Scarborough</LastName>
<AffiliationInfo>
<Affiliation>Mayo Clinic</Affiliation>
</AffiliationInfo>
</Author>
<Author>
<FirstName>Joanna</FirstName>
<LastName>Kay</LastName>
<AffiliationInfo>
<Affiliation>Georgetown University</Affiliation>
</AffiliationInfo>
</Author>
</AuthorList>

**Comment by gnott** [comment]
I will close this as https://github.com/elifesciences/elife-pubmed-feed/issues/43 is a duplicate issue.
