### ISSUE TITLE
PubMed not accept obituaries and in memoriam articles or multiple language abstracts

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#74]
Hi Graham

This does not affect eLife, but affects the reuse of the PubMed tool:

NLM has updated MEDLINE indexing policy. Effective June 1, 2018, PubMed data providers should no longer submit:

* separate citations for the non-English version(s) of an article published in multiple languages. 

* citations for obituaries and in memoriam articles.

Further details about these policy changes are included below.

----------

1.  Multiple Translations of the Same Journal Article. 

Only the English version of multi-language articles will appear in PubMed and be indexed for MEDLINE. In the past, when journals published multiple translations of an article in the same issue, the English version was indexed for MEDLINE, and citations for any non-English versions were included in PubMed but not indexed for MEDLINE. In many cases, users may access the non-English versions of these articles on the publisher's website. 

Data providers may choose to include the non-English abstract with the citation submitted for the English version of the article. See: https://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.Instructions_for_articles.

Technical Bulletin article: https://www.nlm.nih.gov/pubs/techbull/mj18/brief/mj18_multiple_translations_journal_article.html

2. Obituaries and In Memoriam.

Obituaries and in memoriam articles will no longer be cited in PubMed or indexed for MEDLINE.

In the past, many obituaries and in memoriam articles were indexed for MEDLINE based on subjective criteria that lead to inconsistent coverage; if an article was substantive it was cited in PubMed and indexed with MeSH. However, most obituaries and in memoriam articles are not substantive and will no longer be cited and indexed. Substantive biographies will continue to be indexed for MEDLINE. 

Technical Bulletin article: https://www.nlm.nih.gov/pubs/techbull/mj18/brief/mj18_obituaries_in_memoriam.html

RESOURCES:

* Newly revised: What types of articles are accepted for PubMed? https://www.ncbi.nlm.nih.gov/books/NBK3828/#publisherhelp.What_types_of_articles_are 

PubMed Data Provider Support Team – publisher@ncbi.nlm.nih.gov
National Center for Biotechnology Information
U.S. National Library of Medicine

**Comment by Melissa37** [comment]
I think we should ignore this and just close the issue,.

@FAtherden-eLife do you agree?

**Comment by FAtherden-eLife** [comment]
> I think we should ignore this and just close the issue,.

> @FAtherden-eLife do you agree?

Yup! Sounds fine to me - thanks
