### ISSUE TITLE
Add more dataset values based on XML <source> value

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-pubmed-feed#78]
There are a view datasets added to PubMed deposits in an `<Object>` tag. 

It considers the dataset `uri` value and matches against a list of hints for whether the dataset is an NCBI type.

We might be able to add additional datasets by also considering the value of the `<source>` tag in the XML to guess at what the dataset type could be, e.g.

`<source>Dryad Digital Repository</source>`

would indicate it is a PubMed `Dryad` type.

There are some datasets where the uri or DOI is not unique enough to be used as a hint, and using the source value would be an additional way to match it to a PubMed type.

@Melissa37 here's an issue we can describe and discuss possible improvements.

There is also another issue regarding datasets that may overlap with this: https://github.com/elifesciences/elife-pubmed-xml-generation/issues/33

**Comment by Melissa37** [comment]
Yeah, suggest @FAtherden-eLife controls the values in source via Schematron for the PubMed list so you can create a map from one to the other. Current PubMed values list is:

BioProject
Dryad
figshare
GDB
Omim
PDB
PIR
SwissProt
UniMES
UniParc
UniProtKB
UniRef
NCBI:dbgap
NCBI:dbvar
NCBI:genbank
NCBI:genome
NCBI:gensat
NCBI:geo
NCBI:homologene
NCBI:nucleotide
NCBI:popset
NCBI:protein
NCBI:pubchem-bioassay
NCBI:pubchem-compound
NCBI:pubchem-substance
NCBI:refseq
NCBI:snp
NCBI:sra
NCBI:structure
NCBI:taxonomy
NCBI:unigene
NCBI:unists

**Comment by Melissa37** [comment]
Cross linked with https://github.com/elifesciences/schematron-gitbook/issues/123

**Comment by gnott** [comment]
Looking at this a little more closely today to define some potential next steps, I have a few questions.

I ended up using Xquery to generate a list of dataset `<source>` and `<ext-link>` xlink:href values from previous eLife articles. The source values very often look like it has served as the title of the dataset. The parser uses the `<source>` value for the dataset's `title` value in the JSON data for the article.

Would it be possible to restrict the text in `<source>` tags to a small number of pre-defined values, and is that the intention going forward? If so, where will the dataset title go in the XML?

The `xlink:href` value for the URI of a dataset seems to be more indicative of where the dataset if from, and the PubMed library is using this already for the "hint" about which PubMed value to use. We could expand on the list of "hint" values the PubMed library can support.

**Comment by Melissa37** [comment]
>Would it be possible to restrict the text in <source> tags to a small number of pre-defined values, and is that the intention going forward? If so, where will the dataset title go in the XML?

We cannot do that, but we can use Schematron to ensure the ones you need to deliver to PubMed are controlled via Schematron. We'd expect you to ignore those not on the list, but we cannot restrict them

@FAtherden-eLife would you be able to compile the list of values that you check are consistent in Schematron and pass to @gnott - can you cross check with the list above and see whether we should add more?

>The xlink:href value for the URI of a dataset seems to be more indicative of where the dataset if from, and the PubMed library is using this already for the "hint" about which PubMed value to use. We could expand on the list of "hint" values the PubMed library can support.

That is another option. Although I think  Source is might be safer?

**Comment by FAtherden-eLife** [comment]
@gnott, @Melissa37, the Schematron checks that the value of source is correct based on the link on the `pub-id`. I think using source might be safer still however (since this could be changed during proofing for sensible some reason). I will provide a table for the source -> PubMed value mapping.

**Comment by FAtherden-eLife** [comment]
Also using `source` would mean that we don't have a mismatch between the content and the PubMed value.

**Comment by FAtherden-eLife** [comment]
Here's what we check for currently using the Schematron. I will check the archive for any others and update this table:

| PubMed value           | Source value(s)                                     |
|------------------------|-----------------------------------------------------|
| BioProject             | NCBI BioProject                                     |
| Dryad                  | Dryad Digital Repository                            |
| figshare               | figshare                                            |
| GDB                    |                                                     |
| Omim                   |                                                     |
| PDB                    | RCSB Protein Data Bank\|Worldwide Protein Data Bank |
| PIR                    |                                                     |
| SwissProt              |                                                     |
| UniMES                 |                                                     |
| UniParc                |                                                     |
| UniProtKB              |                                                     |
| UniRef                 |                                                     |
| NCBI:dbgap             | NCBI dbGaP                                          |
| NCBI:dbvar             |                                                     |
| NCBI:genbank           | NCBI GenBank                                        |
| NCBI:genome            | NCBI Assembly                                       |
| NCBI:gensat            |                                                     |
| NCBI:geo               | NCBI Gene Expression Omnibus                        |
| NCBI:homologene        |                                                     |
| NCBI:nucleotide        | NCBI Nucleotide                                     |
| NCBI:popset            | NCBI PopSet                                         |
| NCBI:protein           | NCBI Protein                                        |
| NCBI:pubchem-bioassay  |                                                     |
| NCBI:pubchem-compound  |                                                     |
| NCBI:pubchem-substance |                                                     |
| NCBI:refseq            |                                                     |
| NCBI:snp               |                                                     |
| NCBI:sra               | NCBI Sequence Read Archive                          |
| NCBI:structure         |                                                     |
| NCBI:taxonomy          |                                                     |
| NCBI:unigene           |                                                     |
| NCBI:unists            |                                                     |

**Comment by gnott** [comment]
I think I might be understanding more fully now, thanks. I feel like it is worth a discussion point for our weekly call.

I'm looking at a recently published article which may serve as an example: https://elifesciences.org/articles/55320/figures#data, the XML https://github.com/elifesciences/elife-article-xml/blob/master/articles/elife-55320-v2.xml

On journal, the `<source>NCBI Gene Expression Omnibus</source>` continues to be the `title`. From the XML, there is also the `<data-title>` tag, which populates the `details` in the JSON format of the article.

My understanding too is for PubMed deposits, you'd only want the ones that we can match the `<source>` tag value exactly to be included in the PubMed deposits, and we could do away with the 'uri' hint logic. The `<source>` is used as the `elife-article` `Article()` object's `title` property, because that is how it is named in the JSON schema, and is where the data comes from when the `Article()` is populated with values.

We might be able to adapt this to also include a value named `source` so it is more clear how it really isn't a title, but in the JSON schema it is named `title`.

**Comment by Melissa37** [comment]
>On journal, the <source>NCBI Gene Expression Omnibus</source> continues to be the title. From the XML, there is also the <data-title> tag, which populates the details in the JSON format of the article.

I'd never really thought about how items are mapped in the XML to the references, for datasets. This will all change ultimately anyway when we stop presenting them there, so I don't think we need worry about that for now, seems sensible enough for what it's doing, even if not semantic - looks like an example of angling data for display purposes!

>My understanding too is for PubMed deposits, you'd only want the ones that we can match the <source> tag value exactly to be included in the PubMed deposits, and we could do away with the 'uri' hint logic. The <source> is used as the elife-article Article() object's title property, because that is how it is named in the JSON schema, and is where the data comes from when the Article() is populated with values.

I thought you built the PubMed and Crossref deposits from the source XML and not the JSO schema? I think that would be safer

>We might be able to adapt this to also include a value named source so it is more clear how it really isn't a title, but in the JSON schema it is named title.

Again, better to use source XML?

**Comment by gnott** [comment]
I think we may be discussing the PubMed datasets enhancements on two separate issues, but this one more apt for my question at hand.

I've made some progress today in adding the data from the citations/reference list based on their source value. I searched for some values in previously published article XML to see if I'm on the right track, with the understanding that you're probably not adding all the data as references yet, or enforcing the `<source>` tag values.

I noticed some case-sensitivity differences in some recently published articles:

figshare - all lower-case in 10.7554/eLife.45573 bib42
Figshare - upper-case 'F in 10.7554/eLife.52614 bib69
I also found 'FigShare' a couple times

In some older data from datasets section elements I found:

NCBI BioProject
NCBI Bioproject

Considering these may not yet be enforced, for my purposes:

Q. Will the schematron rules enforce case-sensitivity of values?
Q. Would it better to match source values based on case-insensitive strings, or would you have multiple variants in the XML that would map to a particular PubMed assigning authority value?

**Comment by FAtherden-eLife** [comment]
> Would it better to match source values based on case-insensitive strings, or would you have multiple variants in the XML that would map to a particular PubMed assigning authority value?

Yes it would be better to ignore case. The tests currently only enforce the correct case in the `source` in references in the Data availability section, not the reference list. I can create tests which do this, but it would be safer to ignore case if that's simple to implement.

**Comment by gnott** [comment]
I changed it to case-insensitive matching and I think it will work well. The updated code is merged into the library itself, and I'm next to deploy it so we start using it.

Once deployed, it may have some minimal effects already. One of the recent example articles I found was `53243`. There two datasets from the reference list that would have been included in the PubMed deposit if the article were to be published after the code change,

```
<Object Type="PDB">
<Param Name="id">5UUZ</Param>
</Object>
<Object Type="PDB">
<Param Name="id">4X3Z</Param>
</Object>
```

It's interesting to see its current PubMed page at https://pubmed.ncbi.nlm.nih.gov/31999252/. There are datasets listed, but none of those were included in the PubMed deposit we sent January 30th, 2020, so I assume they are copied over from PMC. They all seem to be from the datasets section, but because we were not configured to look for hints on the `uri` values for these, the PubMed deposit library did not include them.

Also, their source values are `<source>Protein Data Bank</source>` which would not match the source name we expect to see in any reference's source name; we are only matching `RCSB Protein Data Bank` and `Worldwide Protein Data Bank`. Of course, you were probably not validating the `Protein Data Bank` in datasets via schematron or other means, and in the future I expect you'll be more precise with naming if you wish to have the dataset included in the PubMed deposit.

All that aside, if `53243` were generated after the code deployment which I should get done today, there would be two datasets included in the deposit, taking from the references list, versus zero datasets prior to the code enhancement.

**Comment by gnott** [comment]
This is added now to the `elifepubmed` library, and it is deployed to be used in the `prod` `elife-bot` going forward. Hopefully all will work as planned. If you notice any errors could you please raise them as new issues? Thanks! I hope you also agree this issue is completed.
