### ISSUE TITLE
<Identifier Source=”ORCID”>http://orcid.org/5555-5555-5555-5555</Identifier>

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-pubmed-feed#8]
Yeah, can provide author ORCIDs to PubMed! Has been added to the VoR xml sample

**Comment by Melissa37** [comment]
Hi Graham

I just realised that we are not providing ORCIDs to PubMed for our VoR content and we should be. It's in the sample XML on GitHub but I guess I forget to remember about it that we can deliver for VoR content.
Can we get that added into the VoR package asap?

Orcids have been bumped to the top of an agenda and so I need to be doing all I can to add their value.

Sorry!!

M

**Comment by gnott** [comment]
I've been checking and I think we've been supporting this for a while now. At least recently I can see one example 08961 from Oct 16th includes the data, batch file elife-2015-10-16-164606-PubMed.xml

```
<Author>
<FirstName>Steffen</FirstName>
<LastName>Preissler</LastName>
<Affiliation>
Cambridge Institute for Medical Research, University of Cambridge, Cambridge, United Kingdom
</Affiliation>
<Identifier Source="ORCID">http://orcid.org/0000-0001-7936-9836</Identifier>
</Author>
```

**Comment by Melissa37** [comment]
Ah, that's the live example I was looking at and I could not find it in the Batch XML we'd sent to PubMed.
Sorry.

So, PubMed does nothing with it! I'll reach out to them and ask why they don't display it.

Cheers

M

**Comment by Melissa37** [comment]
http://jira.elifesciences.org:8080/browse/ELPP-875
